FROM ruby:3.4

WORKDIR /app

RUN gem install bundler --no-document

COPY Gemfile Gemfile.lock /app/
RUN bundle install

COPY . /app

COPY docker/entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/usr/bin/entrypoint.sh"]

CMD ["ruby", "main.rb"]




