FROM ruby:3.4

ENV RAILS_ENV=development \
    BUNDLE_WITHOUT=""

ARG RAILS_ROOT=/app
WORKDIR $RAILS_ROOT

RUN apt-get update -y \
 && apt-get install -y --no-install-recommends \
    nodejs \
    postgresql-client \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

RUN gem install bundler --no-document \
 && gem install rails -v 8.0.0 --no-document

COPY . $RAILS_ROOT

RUN bundle install

COPY docker/entrypoint.sh /usr/bin/entrypoint.sh
RUN chmod +x /usr/bin/entrypoint.sh

EXPOSE 3000

ENV PATH=$RAILS_ROOT/bin:${PATH}

ENTRYPOINT ["/usr/bin/entrypoint.sh"]
CMD ["bin/dev"]
