name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  fetcher:
    name: Fetcher Lint & Test
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/fetcher/Gemfile
    defaults:
      run:
        working-directory: fetcher
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Linter
        run: bundle exec rubocop

      - name: Test
        run: bundle exec rspec

  display:
    name: Display Lint & Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    env:
      RAILS_ENV: test
      DB_HOST: localhost
      BUNDLE_GEMFILE: ${{ github.workspace }}/display/Gemfile
    defaults:
      run:
        working-directory: display
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Linter
        run: bundle exec rubocop

      - name: DB prepare
        run: bundle exec rails db:prepare

      - name: Test
        run: bundle exec rspec

      - name: Cucumber
        run: bundle exec cucumber
